Fix #257: Unbold example commands in quick start
AY2021S2-CS2103-T14-1/tp pull request #297
Opened 2021-04-06 08:04 UTC by benedictkhoomw

## What this does
Fixes #257

## How to test
1. cd to `docs/` folder of the project.
2. Run `bundle exec jekyll serve`.
3. Open the jekyll-hosted website in your browser (default address: http://127.0.0.1:4000).
4. Check that the commands are not bold in the UG Quick Start section.

2021-04-07 14:25 UTC, DrWala submitted a review, later dismissed

2021-04-07 14:27 UTC, DrWala requested changes
Could you merge master in and make sure the conflicts are resolved so that we don't have any unexpected surprises, and another pair of eyes can double-check it the merge to ensure we don't lose any info.

2021-04-07 16:32 UTC, benedictkhoomw commented
> 
> 
> Could you merge master in and make sure the conflicts are resolved so that we don't have any unexpected surprises, and another pair of eyes can double-check it the merge to ensure we don't lose any info.

Done. Thanks for your comment.

2021-04-08 01:03 UTC, DrWala approved these changes
LGTM

2021-04-08 01:03 UTC, merged