Docs(PPP): Add Azeem's PPP
AY2021S2-CS2103-T14-1/tp pull request #321
Opened 2021-04-07 09:40 UTC by DrWala

## What this does
Closes #186

## How to test
1. cd to `docs/` folder of the project.
2. Run `bundle exec jekyll serve`.
3. Open the jekyll-hosted website in your browser (default address: http://127.0.0.1:4000).
4. Check that the About Us page has the changes listed above

2021-04-08 01:05 UTC, colintkn commented on docs/team/azeem.md
>  ## Project: AddressBook Level 3
Can change to SunRez

2021-04-08 05:35 UTC, colintkn commented on docs/team/azeem.md
> +  * What it does: Allows the user to manage the rooms of the hostel/RC
Final detail. But maybe Can add full stop here.

2021-04-09 03:33 UTC, DrWala commented on docs/team/azeem.md
> +  * What it does: Allows the user to manage the rooms of the hostel/RC
Done

2021-04-09 03:33 UTC, DrWala commented on docs/team/azeem.md
>  ## Project: AddressBook Level 3
Good catch thank you

2021-04-09 13:11 UTC, benedictkhoomw requested changes
The link from About Us to your PPP seems to be broken.

2021-04-09 15:02 UTC, benedictkhoomw approved these changes
Link works now. LGTM.

2021-04-09 15:02 UTC, merged